# Config format schema number
format_version: 4
device_num: 1
map_size: 50
device: 'cuda'

use_cache: False
debug: True
data_path: 'init\processed_data'
sample_gap: 20

max_epoch: 50
num_workers: 6
batch_size: 32
lr: 0.0003
weight_decay: 0.0004
data_usage: 100
hidden_dim: 1024
gaussian_comp: 5

pad_num: 0
min_agent: 8
draw: True
context_num: 1

